loki:
  enabled: true
  size: 1Gi
promtail:
  enabled: true
grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
